version: '3.8'

services:

  api:
    container_name: simple-notes-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './:/app:rw'
      - '/app/node_modules/'
    depends_on:
      - db
    networks:
      - api-network

  db:
    container_name:  simple-notes-database
    image: 'mongo'
    ports:
      - '27017:27017'
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes: 
      - "db-volume:/data/db"
    networks:
      - api-network


  # Utility containers
  # For example: docker-compose run --rm api-npm i -D @types/express
  api-npm:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - './:/app'
  api-npx:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npx']
    volumes:
      - './:/app'



volumes:
  db-volume:
    driver: local

networks:
 api-network:
    driver: bridge